services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app        
      - media_volume:/app/media   
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  media_volume: